### ISSUE TITLE
Can't use spectranet special % codes

### ISSUE THREAD

**Issue by markround** [remy/txt2bas#29]
Hi!

I have a Spectrum +3 with a Spectranet interface (https://www.bytedelight.com/?page_id=3515). I am trying to develop BASIC programs for this by running through txt2bas and loading the resulting TAP files from the Spectranet interface.

The Spectranet adds a bunch of new commands to Spectrum basic, all prefixed with a % character - see http://spectrum.alioth.net/doc/index.php/Guide for some examples.

The problem is, I can't use these commands in programs and then run them through txt2bas. For example, when I use `%open`, then the resulting BASIC file gets interpreted as `% OPEN` - it seems to pick up on the `OPEN` token and split it apart from the leading `%` character.

Similarly, strange things happen with other % commands that don't have any recognised tokens in them. Take the example program listed here: http://spectrum.alioth.net/doc/index.php/Guide#Opening_and_closing_files.

In this, line 20 gets turned into `20%oneof100`, with all the spaces removed. 

I'd love to be able to use txt2bas to be able to write Spectranet programs (including stuff for a public TNFS server), but this is a bit of a show-stopper at the moment. I appreciate these are all non-standard Spectrum basic commands, but would there be any way of including these new commands in generated files ? 

One other "gotcha" is that it should only be the % commands that get included literally; some of them e.g. `%load` do also sometimes have valid BASIC tokens included after them, e.g. `%load "screenshot.scr" CODE 16384`.

**Comment by remy** [comment]
Nothing like a reply 3 years later, right? (sorry).

So, this is because txt2bas support the zxnext OS rather than Spectranet. I could see a pull request to add these tokens via a flag, but I don't use Spectranet myself so I'm not familiar and I don't have a way to test.

It also means if you're writing code using VS Code that then relies on this project (which you've not said, but I wanted to cover), you'd have then surface that switch to the VS Code config (since zxnext expects `%` to represent an integer variable).

I'm going to close this for the time being, and I apologise for not replying with the message above some 3 years+ ago!
